name: Generate M3U Playlist

on:
  schedule:
    - cron: '0 22,6,14 * * *'  # 每天 UTC 时间 22:00,6:00,14:00 自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests

      - name: Run generate_m3u
        run: python ${{ github.workspace }}/generate_m3u.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mytvlist.m3u
          git commit -m "Update M3U playlist"
          git push
